"""
Markdown output writer for Obsidian-compatible vaults.

Produces a single .md file per meeting containing YAML frontmatter
(for Obsidian Dataview queries), the AI-generated summary, and
optionally the full timestamped transcript.

File naming uses the configured template with date and a slug
derived from the meeting title.
"""

import logging
import os
import time
from pathlib import Path

import yaml as _yaml
from slugify import slugify

from src.summariser import MeetingSummary
from src.transcriber import Transcript
from src.utils.config import MarkdownConfig

logger = logging.getLogger(__name__)


def _rewrite_frontmatter_title(content: str, new_title: str) -> str:
    """Return *content* with its YAML frontmatter ``title`` set to *new_title*.

    Falls back to returning *content* unchanged if the frontmatter block is
    missing or malformed, rather than risk corrupting the note.
    """
    if content.startswith("---\n"):
        end = content.find("\n---", 4)
        if end != -1:
            block = content[4:end]
            try:
                fm = _yaml.safe_load(block) or {}
            except _yaml.YAMLError:
                fm = {}
            if isinstance(fm, dict):
                fm["title"] = new_title
                new_block = _yaml.dump(
                    fm, default_flow_style=False, allow_unicode=True, sort_keys=False
                ).rstrip()
                return f"---\n{new_block}\n---{content[end + 4 :]}"
    return content


class MarkdownWriter:
    """Writes meeting output to an Obsidian-compatible Markdown vault."""

    def __init__(self, config: MarkdownConfig):
        self._config = config
        # Set when a filesystem error occurs during write(); the orchestrator
        # reads this to emit a pipeline.warning so the UI can surface
        # "Markdown output skipped: <reason>" instead of failing silently.
        self.last_error: str | None = None

    def write(
        self,
        summary: MeetingSummary,
        transcript: Transcript,
        started_at: float,
        duration_seconds: float,
    ) -> Path | None:
        """
        Write the meeting summary and transcript to a .md file.

        Returns the path to the created file, or ``None`` if a filesystem
        error prevented the write (in which case ``last_error`` is set).
        """
        self.last_error = None
        vault_path = Path(self._config.vault_path)
        try:
            os.makedirs(vault_path, exist_ok=True)
        except OSError as e:
            self.last_error = f"Could not create vault directory {vault_path}: {e}"
            logger.error("Markdown write failed: %s", self.last_error)
            return None

        # Build the filename from the configured template.
        date_str = time.strftime("%Y-%m-%d", time.localtime(started_at))
        time_str = time.strftime("%H-%M", time.localtime(started_at))
        title_slug = slugify(summary.title, max_length=60)

        filename = self._config.filename_template.format(
            date=date_str,
            time=time_str,
            slug=title_slug or "meeting",
        )

        # Sanitize filename to prevent directory traversal.
        filename = filename.replace("/", "_").replace("\\", "_").lstrip(".")
        filepath = (vault_path / filename).resolve()
        if not filepath.is_relative_to(vault_path.resolve()):
            raise ValueError(f"Generated filename would escape the vault directory: {filename!r}")

        # Build YAML frontmatter for Obsidian Dataview compatibility.
        duration_min = int(duration_seconds / 60)
        frontmatter = {
            "title": summary.title,
            "date": date_str,
            "time": time_str.replace("-", ":"),
            "duration_minutes": duration_min,
            "word_count": transcript.word_count,
            "tags": summary.tags,
            "type": "meeting-note",
        }
        frontmatter_yaml = _yaml.dump(
            frontmatter, default_flow_style=False, allow_unicode=True
        ).rstrip()

        content_parts = [
            "---",
            frontmatter_yaml,
            "---",
            "",
            summary.raw_markdown,
            "",
            "---",
            "",
            (
                f"*Generated by Context Recall on "
                f"{time.strftime('%Y-%m-%d %H:%M')} — "
                f"{duration_min} min, {transcript.word_count:,} words*"
            ),
        ]

        if self._config.include_full_transcript:
            content_parts.extend(
                [
                    "",
                    "---",
                    "",
                    "## Full Transcript",
                    "",
                ]
            )
            for seg in transcript.segments:
                timestamp = f"**{seg.timestamp}**"
                speaker = f" *{seg.speaker}*:" if seg.speaker else ""
                content_parts.append(f"{timestamp}{speaker} {seg.text.strip()}")
                content_parts.append("")

        content = "\n".join(content_parts)

        # Atomic write: stream to a sibling temp file then os.replace() in
        # place. Prevents partial files if the daemon is killed mid-write or
        # the disk fills up between bytes.
        tmp_path = filepath.with_name(filepath.name + ".tmp")
        try:
            tmp_path.write_text(content, encoding="utf-8")
            os.replace(tmp_path, filepath)
        except OSError as e:
            self.last_error = f"Could not write markdown file {filepath}: {e}"
            logger.error("Markdown write failed: %s", self.last_error)
            # Best-effort cleanup of the temp file; ignore secondary errors.
            try:
                tmp_path.unlink(missing_ok=True)
            except OSError:
                pass
            return None

        logger.info("Markdown written: %s", filepath)
        return filepath

    def rename_note(self, old_path: Path, new_title: str, started_at: float) -> Path | None:
        """Rename a written note to reflect a new title.

        Rewrites the YAML frontmatter ``title`` and renames the file to the
        new title's slug (same template + start time as ``write()``).
        Returns the new path, the (title-updated) old path when the
        computed filename is unchanged, or ``None`` on a filesystem error
        (``last_error`` is set). Raises ``ValueError`` if the target would
        escape the vault, matching ``write()``'s existing behaviour.
        """
        self.last_error = None
        old_path = Path(old_path)
        vault_path = Path(self._config.vault_path)
        try:
            content = old_path.read_text(encoding="utf-8")
        except OSError as e:
            self.last_error = f"Could not read note {old_path}: {e}"
            logger.error("Markdown rename failed: %s", self.last_error)
            return None

        # Recompute the target filename exactly like write().
        date_str = time.strftime("%Y-%m-%d", time.localtime(started_at))
        time_str = time.strftime("%H-%M", time.localtime(started_at))
        title_slug = slugify(new_title, max_length=60)
        filename = self._config.filename_template.format(
            date=date_str, time=time_str, slug=title_slug or "meeting"
        )
        filename = filename.replace("/", "_").replace("\\", "_").lstrip(".")
        new_path = (vault_path / filename).resolve()
        if not new_path.is_relative_to(vault_path.resolve()):
            raise ValueError(f"Rename target would escape the vault directory: {filename!r}")

        new_content = _rewrite_frontmatter_title(content, new_title)

        # Same computed filename: just rewrite the frontmatter in place.
        # Atomic write (tmp + os.replace), same crash-safe pattern as write(),
        # so a crash mid-write can't truncate the only copy of the note.
        if new_path == old_path.resolve():
            tmp_path = old_path.with_name(old_path.name + ".tmp")
            try:
                tmp_path.write_text(new_content, encoding="utf-8")
                os.replace(tmp_path, old_path)
            except OSError as e:
                self.last_error = f"Could not rewrite note {old_path}: {e}"
                logger.error("Markdown rename failed: %s", self.last_error)
                try:
                    tmp_path.unlink(missing_ok=True)
                except OSError:
                    pass
                return None
            return old_path

        # Different filename: avoid clobbering an unrelated existing note.
        if new_path.exists():
            stem, suffix = new_path.stem, new_path.suffix
            n = 2
            while True:
                candidate = new_path.with_name(f"{stem} ({n}){suffix}")
                if not candidate.exists():
                    new_path = candidate
                    break
                n += 1

        tmp_path = new_path.with_name(new_path.name + ".tmp")
        try:
            tmp_path.write_text(new_content, encoding="utf-8")
            os.replace(tmp_path, new_path)
        except OSError as e:
            self.last_error = f"Could not write renamed note {new_path}: {e}"
            logger.error("Markdown rename failed: %s", self.last_error)
            try:
                tmp_path.unlink(missing_ok=True)
            except OSError:
                pass
            return None

        # The rename itself succeeded once the new file is written. Removing
        # the old file is best-effort: if it fails, a stale duplicate is far
        # better than reporting a false failure and orphaning the new file
        # with no path back to it, so this does NOT set last_error or
        # return None.
        try:
            old_path.unlink(missing_ok=True)
        except OSError as e:
            logger.warning("Renamed note written but could not remove old file %s: %s", old_path, e)

        logger.info("Markdown note renamed: %s -> %s", old_path, new_path)
        return new_path
