"""Compose the Markdown note body from a NoteContext.

Phase 1 reproduces the legacy body (summary verbatim, footer, optional
inline transcript). Later phases add the gold-skeleton section assembly,
tables, callouts, My Tasks and transcript render modes.
"""

from __future__ import annotations

import time

from src.output.note_context import NoteContext


def assemble_body(ctx: NoteContext) -> str:
    parts = [ctx.summary_markdown.rstrip(), "", "---", ""]
    parts.append(
        f"*Generated by Context Recall on {time.strftime('%Y-%m-%d %H:%M')}, "
        f"{ctx.duration_minutes} min, {ctx.word_count:,} words*"
    )
    if ctx.transcript_mode == "inline" and ctx.transcript is not None:
        parts += ["", "---", "", "## Full Transcript", ""]
        for seg in ctx.transcript.segments:
            speaker = f" *{seg.speaker}*:" if seg.speaker else ""
            parts.append(f"**{seg.timestamp}**{speaker} {seg.text.strip()}")
            parts.append("")
    return "\n".join(parts)
