"""Compose the Markdown note body from a NoteContext.

Phase 1 reproduces the legacy body (summary verbatim, footer, optional
inline transcript). Later phases add the gold-skeleton section assembly,
tables, callouts, My Tasks and transcript render modes.
"""

from __future__ import annotations

import time

from src.output.note_context import NoteContext

_PRIORITY_EMOJI = {"urgent": "🔺", "high": "⏫", "medium": "🔼", "low": "🔽"}
_INCOMPLETE = {"open", "in_progress"}


def format_my_task(item) -> str:
    """Render one owner task as a Tasks-plugin checkbox line.

    Format: ``- [ ] <title> [#client/x] [#project/y] <emoji> [📅 due]``.
    The client/project tags are what the Meeting Action Items dashboard
    query (contains "#client/" or "#project/") matches on.
    """
    parts = [f"- [ ] {item.title.strip()}"]
    if item.client_tag:
        parts.append(f"#{item.client_tag}")
    if item.project_tag:
        parts.append(f"#{item.project_tag}")
    parts.append(_PRIORITY_EMOJI.get(item.priority, "🔼"))
    if item.due_date:
        parts.append(f"📅 {item.due_date}")
    return " ".join(parts)


def render_transcript(transcript, mode: str) -> str:
    """Render the transcript block for the given mode.

    ``inline`` emits a ## Full Transcript section; ``foldout`` wraps it in a
    collapsible ``> [!quote]-`` callout; ``omit`` and ``linked`` emit nothing
    here (``linked`` is handled by the writer, which knows the vault path).
    """
    if transcript is None or mode in ("omit", "linked"):
        return ""
    rows = []
    for seg in transcript.segments:
        speaker = f" *{seg.speaker}*:" if seg.speaker else ""
        rows.append(f"**{seg.timestamp}**{speaker} {seg.text.strip()}")
    if mode == "foldout":
        body = "\n".join(f"> {r}" for r in rows)
        return "> [!quote]- Full transcript\n" + body
    # inline
    return "## Full Transcript\n\n" + "\n\n".join(rows)


def render_my_tasks(items) -> str:
    """Render the ## My Tasks section, or "" when there are no owner tasks."""
    if not items:
        return ""
    lines = ["## My Tasks", ""]
    lines += [format_my_task(i) for i in items]
    return "\n".join(lines)


def select_owner_tasks(items, owner_identities, owner_display_name) -> list:
    """Filter to the owner's own incomplete action items.

    An item belongs to the owner when its assignee matches an owner
    identity or the owner's display name (case-insensitively). Completed or
    cancelled items are excluded.
    """
    ident = {i.strip().lower() for i in owner_identities if i and i.strip()}
    ident.add((owner_display_name or "").strip().lower())
    out = []
    for item in items:
        assignee = (item.assignee or "").strip().lower()
        if assignee and assignee in ident and item.status in _INCOMPLETE:
            out.append(item)
    return out


def assemble_body(ctx: NoteContext) -> str:
    parts = [ctx.summary_markdown.rstrip(), "", "---", ""]
    parts.append(
        f"*Generated by Context Recall on {time.strftime('%Y-%m-%d %H:%M')}, "
        f"{ctx.duration_minutes} min, {ctx.word_count:,} words*"
    )
    if ctx.transcript_mode == "inline" and ctx.transcript is not None:
        parts += ["", "---", "", "## Full Transcript", ""]
        for seg in ctx.transcript.segments:
            speaker = f" *{seg.speaker}*:" if seg.speaker else ""
            parts.append(f"**{seg.timestamp}**{speaker} {seg.text.strip()}")
            parts.append("")
    return "\n".join(parts)
